### ISSUE TITLE
check-sudt-balance.js failed because of  "missing revert data in call exception"

### ISSUE THREAD

**Issue by BourneNeo** [nervosnetwork/layer2-evm-documentation#5]
I use check-sudt-balance.js to check my sudt balance after succeeded deposit sudt from L1 to L2, it failed, and return  "missing revert data in call exception". 

**Here are my params:**
ETHEREUM_ADDRESS = '0x56a079B315dAeBD310BA9A8B45a1302856b2AA70'
SUDT_PROXY_CONTRACT_ADDRESS = '0xF399694F6fF9f12eeE98f7bB87012f86cA765BE8'

**and the whole process:**
neo@DESKTOP-Q1QBGQQ:~/projects/layer2-evm-documentation/code-examples/5-erc20-proxy$ node check-sudt-balance.js 
Using Ethereum address: 0x56a079B315dAeBD310BA9A8B45a1302856b2AA70
Checking SUDT balance using proxy contract with address: 0xF399694F6fF9f12eeE98f7bB87012f86cA765BE8...
/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/logger/lib/index.js:233
        var error = new Error(message);
                    ^

Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32099,\"message\":\"revert: \",\"data\":{\"failed_reason\":{\"status_code\":\"0x2\",\"status_type\":\"REVERT\",\"message\":\"\"}}}}","error":{"code":-32099,"data":{"failed_reason":{"status_code":"0x2","status_type":"REVERT","message":""}}},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"gas\":\"0x1bad9d8\",\"to\":\"0xf399694f6ff9f12eee98f7bb87012f86ca765be8\",\"data\":\"0x70a0823100000000000000000000000056a079b315daebd310ba9a8b45a1302856b2aa70\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://godwoken-testnet-web3-v1-rpc.ckbapp.dev"}, data="0x", code=CALL_EXCEPTION, version=providers/5.6.1)
    at Logger.makeError (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at checkError (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:76:16)
    at JsonRpcProvider.<anonymous> (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:659:47)
    at step (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32099,\"message\":\"revert: \",\"data\":{\"failed_reason\":{\"status_code\":\"0x2\",\"status_type\":\"REVERT\",\"message\":\"\"}}}}", error={"code":-32099,"data":{"failed_reason":{"status_code":"0x2","status_type":"REVERT","message":""}}}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"gas\":\"0x1bad9d8\",\"to\":\"0xf399694f6ff9f12eee98f7bb87012f86ca765be8\",\"data\":\"0x70a0823100000000000000000000000056a079b315daebd310ba9a8b45a1302856b2aa70\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://godwoken-testnet-web3-v1-rpc.ckbapp.dev", code=SERVER_ERROR, version=web/5.6.0)
      at Logger.makeError (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/logger/lib/index.js:233:21)
      at Logger.throwError (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/logger/lib/index.js:242:20)
      at /home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:305:32
      at step (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":44,"error":{"code":-32099,"message":"revert: ","data":{"failed_reason":{"status_code":"0x2","status_type":"REVERT","message":""}}}}',
    error: Error: revert: 
        at getResult (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
        at processJsonFunc (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:348:22)
        at /home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:280:46
        at step (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/neo/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32099,
      data: {
        failed_reason: { status_code: '0x2', status_type: 'REVERT', message: '' }
      }
    },
    requestBody: '{"method":"eth_call","params":[{"gas":"0x1bad9d8","to":"0xf399694f6ff9f12eee98f7bb87012f86ca765be8","data":"0x70a0823100000000000000000000000056a079b315daebd310ba9a8b45a1302856b2aa70"},"latest"],"id":44,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://godwoken-testnet-web3-v1-rpc.ckbapp.dev'
  },
  data: '0x'
}

**Comment by Flouse** [comment]
The document and `check-sudt-balance.js` are OK.
Please follow this [GitHub Action workflow](https://github.com/Flouse/layer2-evm-documentation/blob/2795006/.github/workflows/sudt-erc20-proxy.yml) and try again.

## Tested
 https://github.com/Flouse/layer2-evm-documentation/runs/6132947106?check_suite_focus=true#step:7:25

Logs:
```js
SUDT_PROXY_CONTRACT_ADDRESS=0x7D656a9fadFb53b4D1204f54892c120E45F2f298 \
  ETHEREUM_ADDRESS=0x890616016250e494F2dA742496C8Ec491546525f \
    node check-sudt-balance.js
  echo "================================================================="
  SUDT_PROXY_CONTRACT_ADDRESS=0x7D656a9fadFb53b4D1204f54892c120E45F2f298 \
  ETHEREUM_ADDRESS=0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73 \
    node check-sudt-balance.js
  echo "================================================================="
  SUDT_PROXY_CONTRACT_ADDRESS=0x7D656a9fadFb53b4D1204f54892c120E45F2f298 \
  ETHEREUM_ADDRESS=0xE802b671367Dd060b89f518217e732F7c74025f5 \
    node check-sudt-balance.js
  echo "================================================================="
  SUDT_PROXY_CONTRACT_ADDRESS=0x7D656a9fadFb53b4D1204f54892c120E45F2f298 \
  ETHEREUM_ADDRESS=0x56a079B315dAeBD310BA9A8B45a1302856b2AA70 \
    node check-sudt-balance.js
  shell: /usr/bin/bash -e {0}
  env:
    GODWOKEN_WEB3_RPC: https://godwoken-testnet-web3-v1-rpc.ckbapp.dev
    SUDT_ID: 11243
    ETHEREUM_ADDRESS: 0x890616016250e494F2dA742496C8Ec491546525f

Using Ethereum address: 0x890616016250e494F2dA742496C8Ec491546525f
Checking SUDT balance using proxy contract with address: 0x7D656a9fadFb53b4D1204f54892c120E45F2f298...
BigNumber { value: "20" }
=================================================================
Using Ethereum address: 0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73
Checking SUDT balance using proxy contract with address: 0x7D656a9fadFb53b4D1204f54892c120E45F2f298...
BigNumber { value: "80" }
=================================================================
Using Ethereum address: 0xE802b671367Dd060b89f518217e732F7c74025f5
Checking SUDT balance using proxy contract with address: 0x7D656a9fadFb53b4D1204f54892c120E45F2f298...
BigNumber { value: "80" }
=================================================================
Using Ethereum address: 0x56a079B315dAeBD310BA9A8B45a1302856b2AA70
Checking SUDT balance using proxy contract with address: 0x7D656a9fadFb53b4D1204f54892c120E45F2f298...
BigNumber { value: "80" }
```
