### ISSUE TITLE
Failed to deposit layer 1 sudt token into layer 2

### ISSUE THREAD

**Issue by Dawn-githup** [nervosnetwork/layer2-evm-documentation#6]
> env: kicker image: commit 94a8ef16bf92218332941fa89c8892d889526692 (HEAD -> develop

INSERT_TESTNET_RPC_URL、INSERT_INDEXER_RPC_URL 
Failed to deposit using local & Public nodes

> have enough balance.Use local node deposit to prompt me that L1 balance is insufficient 

error message： 
```
Error: Not enough capacity in from infos!
    at Object.transfer (/home/dawn/projects/godwoken-examples/node_modules/@ckb-lumos/common-scripts/lib/sudt.js:507:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async sendTx (/home/dawn/projects/godwoken-examples/packages/tools/lib/account/deposit-sudt.js:32:18)
    at async Command.run (/home/dawn/projects/godwoken-examples/packages/tools/lib/account/deposit-sudt.js:85:48)
```
> have enough balance.Use public node deposit

error message：Timeout for waiting deposit success in Godwoken, please check with account id: undefined by yourself

**Comment by Flouse** [comment]
Please follow this [GitHub Action workflow](https://github.com/Flouse/layer2-evm-documentation/blob/7c4ed74/.github/workflows/issue-sudt.yml) and try again.
It was tested in https://github.com/Flouse/layer2-evm-documentation/runs/6124357130?check_suite_focus=true#step:10:109
